/**
 * Bot Spec v1 — declarative definition of a single bot deployment unit.
 *
 * This is the data contract for the AI Bot Orchestrator pipeline:
 *   Control Bot → reads/writes BotSpec → generators produce compose/agent config.
 *
 * Stage 7A scope: schema + YAML I/O only.  No generators, registry, or lifecycle.
 */

import { z } from "zod";

/**
 * Regex for bot IDs: lowercase alphanumeric + hyphens, must start with a letter or digit.
 * Used as container name suffix, agent routing key, and filesystem directory name.
 */
const BOT_ID_PATTERN = /^[a-z0-9][a-z0-9-]*$/;

/**
 * Model configuration for the bot.
 *
 * Currently only `id` (provider/model slug).  Structured as an object so future
 * stages can add fields like `fallbacks`, `temperature`, `contextTokens` without
 * a breaking schema change.
 */
export const BotModelSchema = z.object({
  id: z.string().default("anthropic/claude-haiku-4-5"),
});

/**
 * Tool access control.
 *
 * Semantics (matches AgentConfig.tools convention):
 * - `allowlist` present → only these tools are available
 * - `denylist` present → these tools are removed from the available set
 * - Both present → final set = allowlist − denylist
 * - Neither present → all tools available (inherited from agent defaults)
 */
export const BotToolsSchema = z.object({
  allowlist: z.array(z.string()).optional(),
  denylist: z.array(z.string()).optional(),
});

export const BotSpecV1 = z.object({
  /** Schema version — enables future migrations. Must be 1 for this version. */
  version: z.literal(1),

  /** Globally unique identifier (kebab-case).  Used for container name, agent id, routing. */
  id: z
    .string()
    .regex(
      BOT_ID_PATTERN,
      "id must be lowercase alphanumeric with hyphens, starting with a letter or digit",
    ),

  /** Human-readable display name. */
  name: z.string().min(1),

  /** One-line purpose description (optional). */
  description: z.string().optional(),

  /** LLM model configuration. */
  model: BotModelSchema.default({ id: "anthropic/claude-haiku-4-5" }),

  /**
   * Skills to mount on this bot (names reference skills/ directory entries).
   *
   * Empty array = no skills.  Omitted = inherits agent defaults.
   *
   * Future: may upgrade to Array<string | { name: string; config: Record<string, unknown> }>
   * for per-skill configuration, but string[] is sufficient for 7A/7B.
   */
  skills: z.array(z.string()).default([]),

  /** Tool access control (optional). See BotToolsSchema for semantics. */
  tools: BotToolsSchema.optional(),

  /**
   * User-declared additional environment variables injected into the bot container.
   *
   * System-reserved env vars (OPENCLAW_GATEWAY_TOKEN, OPENCLAW_DEFAULT_MODEL, etc.)
   * are generated by the compose generator in Stage 7B — not declared here.
   */
  env: z.record(z.string(), z.string()).default({}),

  /**
   * Gateway port for this bot instance.
   * If omitted, the orchestrator auto-assigns a port (Stage 7B).
   */
  gatewayPort: z.number().int().min(1).max(65535).optional(),

  /** Whether this bot should be deployed.  false = skip during orchestration. */
  enabled: z.boolean().default(true),

  /**
   * Execution runtime for this bot.
   *
   * - "docker"      (default) — runs as an isolated container via docker compose
   * - "in-process"  — runs inside the main gateway process (Stage 11B; no container)
   *
   * Omit for docker (backward-compatible).
   */
  runtime: z.enum(["docker", "in-process"]).default("docker").optional(),

  /**
   * Telegram channel configuration for docker-runtime bots.
   *
   * tokenFile: host-side path to a file containing the Telegram bot token.
   *   The deploy step volume-mounts this file into the container at
   *   /home/node/.openclaw/secrets/<id>.telegram-token
   *   Never store the token value directly in the spec YAML.
   *
   * allowFrom: Telegram user IDs allowed to DM this bot.
   *   Written into the generated openclaw.json for the container.
   */
  telegram: z
    .object({
      tokenFile: z.string().optional(),
      allowFrom: z.array(z.union([z.string(), z.number()])).optional(),
    })
    .optional(),

  /**
   * Path to the existing docker compose project directory for this bot.
   *
   * When set, stop/restart operations use
   * `docker compose --project-directory <composeProjectDir> <cmd>`
   * instead of generating a temporary compose file.  Use this to adopt
   * a bot that was deployed independently (not via /bot-deploy).
   *
   * Omit for bots deployed through the normal /bot-deploy flow.
   */
  composeProjectDir: z.string().optional(),

  /**
   * Override for the Docker container name used by docker inspect (status).
   *
   * Defaults to `openclaw-<id>` (generated by generate-compose-service).
   * Set this when the existing container was created with a different name
   * (e.g. `finance-bot-finance-bot-1` from a standalone compose project).
   */
  containerName: z.string().optional(),
});

export type BotSpec = z.infer<typeof BotSpecV1>;
export type BotModel = z.infer<typeof BotModelSchema>;
export type BotTools = z.infer<typeof BotToolsSchema>;
